### ISSUE TITLE
 possible EventEmitter memory leak detected. 11 upgrade listeners added. Use emitter.setMaxListeners() to  increase limit.

### ISSUE THREAD

**Issue by wangduanduan** [chimurai/http-proxy-middleware#108]
(node) warning: possible EventEmitter memory leak detected. 11 upgrade listeners added. Use emitter.setMaxListeners() to
 increase limit.
Trace
    at Server.addListener (events.js:239:17)
    at catchUpgradeRequest (E:\work\saas\node_modules\.npminstall\http-proxy-middleware\0.17.1\http-proxy-middleware\lib
\index.js:51:16)
    at middleware (E:\work\saas\node_modules\.npminstall\http-proxy-middleware\0.17.1\http-proxy-middleware\lib\index.js
:46:13)
    at Layer.handle [as handle_request] (E:\work\saas\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\work\saas\node_modules\express\lib\router\index.js:312:13)
    at E:\work\saas\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (E:\work\saas\node_modules\express\lib\router\index.js:330:12)
    at next (E:\work\saas\node_modules\express\lib\router\index.js:271:10)
    at logger (E:\work\saas\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (E:\work\saas\node_modules\express\lib\router\layer.js:95:5)

### Setup

* http-proxy-middleware: _version_0.17.1
* server: _connect/express/browser-sync..._ + _version_
* other relevant modules

#### proxy middleware configuration
```javascript
// filePath: /app.js
...
var sdkProxy = proxy('/mvc/stomp',{
    target       :sdk_target,
    changeOrigin :true,
    ws           :true,
    logLevel     :'info'
});
...
var app = express();
...
app.use(sdkProxy);
...
module.exports = app;


// filePath: /bin/www
var app   = require('../app');
...
var server = http.createServer(app);

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
...
```

## i don't kown how to minitor the upgrade event
in your websocket example, everything just in one file。but in express project, it hava /app.js and /bin/www, i don't konw how to handler this. 

looking forward to your reply.

**Comment by chimurai** [comment]
The code snippets doesn't seem to reveal the cause of the issue.

Somewhere you are constantly subscribing to an event, instead of subscribing it once.

Think StackOverflow is a better place to troubleshoot your project/setup.

Feel free to re-open the issue if you think the memory leak is caused by http-proxy-middleware. In that case, please provide a minimal working setup to help identifying the issue.

Thanks.

**Comment by burtontanner** [comment]
This happened to me when I created the middleware on every single request. I saw this exact error and it was fixed by only creating the middleware once. Hope this helps.
