### ISSUE TITLE
TypeError: Header name must be a valid HTTP Token ["cache -control"]

### ISSUE THREAD

**Issue by Pines-Cheng** [chimurai/http-proxy-middleware#185]
the start is well。
```
[HPM] GET /v2/goods/goods_summary?access_token=b1c9aeb1dce5eb26672a2d72041276b3&t=1500448519850 -> https://api.dinghuo123.com
```

when fetch data,throw error.
### ERROR
```
_http_outgoing.js:366
    throw new TypeError(
    ^

TypeError: Header name must be a valid HTTP Token ["cache -control"]
    at ServerResponse.setHeader (_http_outgoing.js:366:11)
    at setHeader (/Users/spider/Work/ydh/ircloud-ydh-agent/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:94:15)
    at /Users/spider/Work/ydh/ircloud-ydh-agent/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:116:7
    at Array.forEach (native)
    at Array.writeHeaders (/Users/spider/Work/ydh/ircloud-ydh-agent/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:111:35)
    at ClientRequest.<anonymous> (/Users/spider/Work/ydh/ircloud-ydh-agent/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:166:20)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:563:20)
```

### Setup

http-proxy-middleware@0.17.4
http-proxy@1.16.2
express@4.15.3

#### proxy middleware configuration
```javascript
'^/v2/**': {
      target: 'https://api.dinghuo123.com',
      changeOrigin: true,
      logLevel: 'debug'
    }
```

**Comment by chimurai** [comment]
The extra space in your `"cache -control"` probably makes it invalid.
Don't think it's an HPM issue.

**Comment by chimurai** [comment]
Closing issue. Feel free to re-open if you think it's a bug in HPM.
