### ISSUE TITLE
onProxyReq error: trapped error code: message:Can't set headers after they are sent. stack:Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by wanglong167** [chimurai/http-proxy-middleware#343]
https://github.com/nodejitsu/node-http-proxy/issues/1292

**Comment by wanglong167** [comment]
proxy.once('proxyReq',

**Comment by wanglong167** [comment]
"http-proxy-middleware": "^0.17.4",

**Comment by paulcodiny** [comment]
+1 here
```
Error: Can't set headers after they are sent.
[proxy:test] [1]     at validateHeader (_http_outgoing.js:491:11)
[proxy:test] [1]     at ClientRequest.setHeader (_http_outgoing.js:498:3)
[proxy:test] [1]     at ProxyServer.onProxyReq (.../scripts/test-server.js:45:14)
[proxy:test] [1]     at ProxyServer.emit (.../node_modules/http-proxy-middleware/node_modules/eventemitter3/index.js:184:35)
[proxy:test] [1]     at ClientRequest.<anonymous> (.../node_modules/http-proxy-middleware/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:132:27)
[proxy:test] [1]     at emitOne (events.js:121:20)
[proxy:test] [1]     at ClientRequest.emit (events.js:211:7)
[proxy:test] [1]     at tickOnSocket (_http_client.js:657:7)
[proxy:test] [1]     at onSocketNT (_http_client.js:673:5)
[proxy:test] [1]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

it seems that if the package is paired with `agent` property, the `agent` sets the headers earlier and then `onProxyReq` is not working anymore.

**Comment by tonokim** [comment]
+1

**Comment by maxevilmind** [comment]
same here,
trying to add a cookie onProxyReq with setHeader and getting `Error: Can't set headers after they are sent.`

**Comment by wanglong167** [comment]
proxyTimeout:20000     @paulcodiny   @tonokim  @maxevilmind

**Comment by johncollierclarivate** [comment]
Running into this issue also, can this be re-opened?
