### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by cdisk** [chimurai/http-proxy-middleware#412]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client.

I use the vue webpack config this funtions.
I want to use both `pathRewrite` and `followRedirects`.
But When I add `followRedirects` config attribute，the console show me this error.

### Steps to reproduce
1. create vue project.
2. add vue.config.js
3. add `proxy` config to `vue.config.js` file.
4. add `pathRewrite` and `followRedirects` to `proxy` node.
5. run command `yarn serve` to start project.
6. use ajax call target url in browser.
7. the yarn console display following errors and stop the project:
`_http_outgoing.js:485
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ClientRequest.setHeader (_http_outgoing.js:485:11)
    at RedirectableRequest.setHeader (/root/workspaces/sqwl/hzsc-pc/node_modules/http-proxy/node_modules/follow-redirects/index.js:118:24)
    at ProxyServer.onProxyReq (/root/workspaces/sqwl/hzsc-pc/node_modules/@vue/cli-service/lib/util/prepareProxy.js:97:20)
    at ProxyServer.emit (/root/workspaces/sqwl/hzsc-pc/node_modules/eventemitter3/index.js:184:35)
    at RedirectableRequest.<anonymous> (/root/workspaces/sqwl/hzsc-pc/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:132:27)
    at RedirectableRequest.emit (events.js:223:5)
    at ClientRequest.eventHandlers.<computed> (/root/workspaces/sqwl/hzsc-pc/node_modules/http-proxy/node_modules/follow-redirects/index.js:17:24)
    at ClientRequest.emit (events.js:228:7)
    at tickOnSocket (_http_client.js:684:7)
    at onSocketNT (_http_client.js:723:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

please help me.

**Comment by uranium93** [comment]
any updates about this Issue ? :/

**Comment by Halfist** [comment]
After new research I figured out that `bypass` suffers from https://github.com/webpack/webpack-dev-server/issues/829.

Luckily, you could substitute it with `pathRewrite` like this.

```
// for non-GET requests
pathRewrite: (path, request) => {
    request.method === 'GET';
    return '/path/to/mock.json';
}

// for GET requests
pathRewrite: () => '/path/to/mock.json'
```

**Comment by uranium93** [comment]
Little update regarding this. we faced an issue with same error message using express with `http-proxy-middleware` and the issue was that in implementation `next()` was called twice, once in the middleware and the other one onError without return.

**Comment by chimurai** [comment]
Closing stale issue.

Feel free to open a new issue if you are still experience this issue in the latest version
