### ISSUE TITLE
[HPM] GET /api -> https://proxy/ TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":path"]

### ISSUE THREAD

**Issue by bhagn** [chimurai/http-proxy-middleware#440]
### Is this a bug report?

A proxy request gets terminated immediately by giving an error that says the Header name `[:path]` is invalid. This works fine on older version of node (ex: 6.x), but fails on all the later versions. 

### Steps to reproduce
```
createProxyMiddleware('/api', {
    target: 'https://localhost:5000',
    changeOrigin:true,
    logLevel: 'debug',
    secure: false,
    ws: true,
    autoRewrite: true
})
```

### Expected behavior
Expect the proxy to go through and make a request

### Actual behavior
Get this exception:

```
node:27533) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)
[HPM] GET /api/profile -> https://localhost:5000/
TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":path"]
    at ClientRequest.setHeader (_http_outgoing.js:484:3)
    at new ClientRequest (_http_client.js:206:14)
    at Object.request (https.js:303:10)
    at Array.stream (/ui.builder/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
    at ProxyServer.<anonymous> (/ui.builder/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at HttpProxyMiddleware.<anonymous> (/ui.builder/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:29:32)
    at Generator.next (<anonymous>)
    at fulfilled (/ui.builder/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

### Setup

gulp -> connect -> http-proxy-middleware

#### client info

OS: Mac OS 10.15.4
Node: 8.17.0, 11.15.0
npm: 6.7.0

**Comment by chimurai** [comment]
Please provide a reproducible example with a description of your setup. To avoid a lot of guess work.

From a quick search it might be related to your http/2 setup and pseudo header fields?
