### ISSUE TITLE
[FEATURE] HTTP->HTTPS using p12 certificates

### ISSUE THREAD

**Issue by FrancescoDiMaggio** [chimurai/http-proxy-middleware#591]
**Describe the feature you'd love to see**

I would like to proxy local traffic to external services using P12 certificates + string Passphrase.
Other node proxies try to do this but I'm not sure about the result.

Is this scenario already present in this project?

**Comment by chimurai** [comment]
Think you can try to configure the target as described here: https://stackoverflow.com/a/31225722/3841188

`http-proxy-middleware`'s target option is basically `http-proxy` `target`. Here you can find more details:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy/index.d.ts#L31-L34

Happy to add a [p12 recipe](https://github.com/chimurai/http-proxy-middleware/tree/master/recipes) if you manage to make it work.

**Comment by FrancescoDiMaggio** [comment]
I'll try this morning (in my timezone obv) and let you know about it!
Thank you mate.

**Comment by FrancescoDiMaggio** [comment]
At the moment this is the code I'm running:
I just removed some critical informations...
I can certity that I can view the certificate using keytool routine, che passphrase I'm using is correct and valid.

```javascript
const express = require("express");
const { createProxyMiddleware } = require("http-proxy-middleware");
const fs = require("fs");
const port = 5500;

const app = express();

const proxyParameters = {
    target: {
        protocol: 'https:',
        host: '10.182.152.XX',
        port: 443,
        pfx: fs.readFileSync('path/to/cert.p12'),
        passphrase: 'passphrase'
    },
    changeOrigin: true
}

app.use("/EB1-ESA-WS/services/rest/apiOilManagement/sendReceipt", createProxyMiddleware(proxyParameters))

app.listen(port, () => {
    console.log(`Proxy from listening on port ${port}!`);
});
```

And I get this error...

```bash
  | Error: passed a null parameter
  |     at Object.createSecureContext (_tls_common.js:210:19)
  |     at Object.connect (_tls_wrap.js:1160:48)
  |     at Agent.createConnection (https.js:120:22)
  |     at Agent.createSocket (_http_agent.js:227:26)
  |     at Agent.addRequest (_http_agent.js:185:10)
  |     at new ClientRequest (_http_client.js:258:16)
  |     at Object.request (https.js:289:10)
  |     at Array.stream (/home/maudev1/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
  |     at ProxyServer.<anonymous> (/home/maudev1/proxy/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
  |     at HttpProxyMiddleware.<anonymous> (/home/maudev1/proxy/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:31:32)
```

Any idea?

**Comment by chimurai** [comment]
There _is_ documentation. (Forgot about it) 😄

https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/https.md#proxy-to-an-https-server-using-a-pkcs12-client-certificate

Looks like you did practically the same.

Maybe you can try to add an `agent` next to `target` like this example: https://github.com/http-party/node-http-proxy/blob/master/examples/http/proxy-http-to-https.js#L40

**Comment by FrancescoDiMaggio** [comment]
Ok so right now I have this configuration:

```js
const express = require("express");
const { createProxyMiddleware } = require("http-proxy-middleware");
const fs = require("fs");
const https = require("https");
const port = 5500;

const app = express();

const proxyParameters = {
    target: {
        protocol: 'https:',
        host: '10.182.152.XX',
        port: 443,
        pfx: fs.readFileSync('path/to/cert.p12'),
        passphrase: 'passphrase'
    },
    agent: https.globalAgent,
    changeOrigin: true
}

app.use("/EB1-ESA-WS/services/rest/apiOilManagement/sendReceipt", createProxyMiddleware(proxyParameters))

app.listen(port, () => {
    console.log(`Proxy listening on port ${port}!`);
});
```

And at the moment, this is still the result:

```bash
2| Error: passed a null parameter
2|     at Object.createSecureContext (_tls_common.js:210:19)
2|     at Object.connect (_tls_wrap.js:1160:48)
2|     at Agent.createConnection (https.js:120:22)
2|     at Agent.createSocket (_http_agent.js:227:26)
2|     at Agent.addRequest (_http_agent.js:185:10)
2|     at new ClientRequest (_http_client.js:258:16)
2|     at Object.request (https.js:289:10)
2|     at Array.stream (/home/maudev1/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
2|     at ProxyServer.<anonymous> (/home/maudev1/proxy/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
2|     at HttpProxyMiddleware.<anonymous> (/home/maudev1/proxy/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:31:32)
```

It's kinda the same... so I'm totally unsure about this thing ahahah

**Comment by chimurai** [comment]
Feels like there is something wrong with your certificate.

Are you sure the certificate and its contents are valid?

To inspect certificate: `openssl pkcs12 -info -infile cert.p12 `

https://github.com/edenhill/librdkafka/issues/3002#issuecomment-661673024

**Comment by FrancescoDiMaggio** [comment]
I can totally confirm that the certificate is valid and is correctly working with the passphrase:

```
[root@mpaygw EXTERNAL]# openssl pkcs12 -info -in cert.p12
Enter Import Password: passphrase
MAC Iteration 100000
MAC verified OK
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-..., Iteration 50000
Certificate bag
Bag Attributes
    friendlyName: ...

[...]

Rq6xfFERMThJt0aUybHuOOHR29JsOsLk8P+5G2j7Dj/I2n4=
-----END CERTIFICATE-----
```

😭

**Comment by chimurai** [comment]
I'm afraid there little I can do, unless you can provide an isolated working example with a demo certificate which has the same issue.

**Comment by FrancescoDiMaggio** [comment]
I solved my issue by using another library, making a real node-express server, using axios to make the call and loading the whole CA certificate on the physical machine.
Here is the code running.

```js
'use strict';

const fs = require('fs');
const axios = require("axios")
const https = require("https");

const express = require("express");
const port = 5550;
const bodyParser = require('body-parser')
const app = express();
app.use(bodyParser.json())

require('axios-debug-log')({
  request: function (debug, config) {
    debug('Request with ' + config.headers['content-type'])
  },
  response: function (debug, response) {
    debug(
      'Response with ' + response.headers['content-type'],
      'from ' + response.config.url
    )
  },
  error: function (debug, error) {
    debug('Boom ', error)
  }
})

app.post("/EB1-ESA-WS/services/rest/apiOilManagement/sendReceipt/axios", async (req, res) => {

  console.log("/// AXIOS HANDLER ///")
  console.log(`/ REQUEST TIMESTAMP ${new Date().toISOString()}`)

  try {
    let response = await axios.post(
      `https:/URL/sendReceipt`,
      req.body,
      {
        httpsAgent: new https.Agent({ ca: fs.readFileSync('/home/path/to/ca.pem') }),
        headers: {
          "content-type": "application/json",
          authorization: req.headers.authorization,
        }
      }
    )
    res.send(response.data)
  }
  catch (e) {
    console.log(`EXCEPTION -> ${e}`)
    res.send({})
  }
})

app.listen(port, () => {
  console.log(`CustomRequest ready on port ${port}`)
})
```

I'm using pm2 as Process Manager and this is the starting config:

```js
module.exports = {
  apps: [{
    name: 'customRequest',
    script: './customRequest.js',

    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '2G',
    env: {
      NODE_ENV: 'development',
      DEBUG: "axios"
    }
  }]
};
```

@chimurai thank you so much for your help, maybe in the future I'll try to support this project.
Cheers!

**Comment by chimurai** [comment]
@FrancescoDiMaggio, found this PR in `http-proxy` https://github.com/http-party/node-http-proxy/pull/1324/files

It suggests to use the `ssl` property in `target` for the p12 certficate.

```js
const proxyParameters = {
    target: {
        protocol: 'https:',
        host: '10.182.152.XX',
        port: 443,
        ssl: {
            pfx: fs.readFileSync('path/to/cert.p12'),
            passphrase: 'passphrase'
        },
    },
    changeOrigin: true
}
```

Curious to hear if this configuration works...
