### ISSUE TITLE
Hono Support for http-proxy-middleware

### ISSUE THREAD

**Issue by shaaridev** [chimurai/http-proxy-middleware#992]
### Describe the feature you'd love to see

Hi,

Integrating support for Hono within http-proxy-middleware will be an awesome feature., especially considering Hono's widespread popularity as a web framework compatible with Node.js, Deno, and Bun.

[Github Hono](https://github.com/honojs/hono)
[Hono](https://hono.dev/)

**Comment by chimurai** [comment]
happy to receive a PR / recipe for Hono

**Comment by branaway** [comment]
tried running a sample with bun, I got this:

```
TypeError: undefined is not an object (evaluating 'server.on')
    at <anonymous> (/Users/bran/localProjects/Slides/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:56:17)
    at <anonymous> (/Users/bran/localProjects/Slides/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:50:22)
    at processTicksAndRejections (native:7:39)
```

**Comment by mrvnklm** [comment]
I can recommend ElysiaJS for anyone being stuck here.

**Comment by branaway** [comment]
ElysiaJS is a high-level web framework. I'm testing the proxy here.
